#!/bin/bash

#a script for monitoring cpu temp, memory usage, and to report # of packages that need to be upgraded. Requires lm-sensors to be installed, and sensors-detect to be run once.

NumP=$(apt-get upgrade -s | grep upgraded | awk 'NR==2 {print $1}')

while [ '1==1' ]
   do
	echo -e "\n---System Monitoring---"
	   
	# sensors | sed Tctl is for AMD CPUs, and sensors | sed Package is for Intel
	echo -n -e "\nCpu Temperature: "&& sensors | sed -nE '/Package:/s/[^+]*\+([[:digit:]]+).*/\1/p' | head -1 && sensors | sed -nE '/Tctl:/s/[^+]*\+([[:digit:]]+).*/\1/p' | head -1

	#memory - uses free to report memory and swap

	echo -e "\nMemory Usage"
	echo -n "	Total Memory:  " && free -h | awk 'NR==2 {print $2}'
	echo -n "	Memory Free:   " && free -h | awk 'NR==2 {print $4}'
	echo -n "	Memory Used:   " && free -h | awk 'NR==2 {print $3}'
	echo -n "	Memory Cached: " && free -h | awk 'NR==2 {print $6}'

	echo -e "\nSwap Usage"
	echo -n "	Total Swap: " && free -h | awk 'NR==3 {print $2}'
	echo -n "	Swap Free:  " && free -h | awk 'NR==3 {print $4}'
	echo -n "	Swap Used:  " && free -h | awk 'NR==3 {print $3}'

	#number of packages needing an upgrade

	echo -n -e  "\nIf the system is upgraded" $NumP "packages will be updated\n\n"

	#breaks loop for 60s

	sleep 60 
done
